title: Muhanad Amous
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1151982371229678
  brandStrength: 0.125
  rhythmicContrast: 0.9969434808008373
  brandColors:
    - '#89b3e1'
    - '#aa9381'
    - '#040402'
    - '#614e3d'
    - '#e6ded4'
  lightness: 0.5325161064974964
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Muhanad Amous
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.75542
layout_spectrum: 0.2239527
