name: Muhanad Amous
favicon: null
layout_spectrum: 0.80301
typography_spectrum: 0.75542
title: Muhanad Amous
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89b3e1'
    - '#aa9381'
    - '#040402'
    - '#614e3d'
    - '#e6ded4'
  brandStrength: 0.125
  lightness: 0.5325161064974964
  saturation: 0.11519823712296784
  rhythmicContrast: 0.9969434808008373
purpose: []
