name: Muhanad Amous
favicon: null
layout_spectrum: 0.18281
typography_spectrum: 0.70041838218458
title: Muhanad Amous
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fb5da'
    - '#303d46'
    - '#7c614c'
    - '#faead9'
    - '#050603'
  brandStrength: 0.125
  lightness: 0.5325161064974964
  saturation: 0.11519823712296784
  rhythmicContrast: 0.9969434808008373
purpose: []
