name: Muhanad Amous
favicon: null
layout_spectrum: 0.93152
typography_spectrum: 0.70041838218458
title: Muhanad Amous
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c8cb'
    - '#eeeff1'
    - '#9f9f97'
    - '#1c2220'
    - '#827b6b'
  brandStrength: 0.42958943522535264
  lightness: 0.5325161064974964
  saturation: 0.11519823712296784
  rhythmicContrast: 0.9969434808008373
purpose: []
